services:
  management-system:
    image: management-system:latest
    container_name: management-system
    build:
      context: .
    environment:
      - DB_HOST_CONTAINER=postgres
      - DOCKER_ENV=true
      - POSTGRES_PORT=${POSTGRES_PORT_CONTAINER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8123:8123"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: management-system-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}"

volumes:
  postgres_data:
