openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server

paths:
  /users:
    get:
      responses:
        '200':
          description: Get all users
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Get a user by ID
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'

  /articles:
    get:
      responses:
        '200':
          description: Get all articles
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Article'

components:
  schemas:
    User:
      type: object
      x-go-name: UserDto
      required:
          - id
          - name
      properties:
          id:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
          name:
            type: string
            example: Alice

    Article:
      type: object
      x-go-name: ArticleDto
      required:
          - id
          - title
          - user_id
          - created_at
      properties:
          id:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
          title:
            type: string
            example: "Hello, world!"
          user_id:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
          description:
            type: string
            example: "This is a description of an article"
          created_at:
            type: string
            format: date-time
            example: "2021-01-01T00:00:00Z"
