openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /ping:
    get:
      responses:
        '200':
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'

  /users:
    get:
      responses:
        '200':
          description: Get all users
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'

components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong

    User:
      type: object
      required:
          - id
          - name
      properties:
          id:
            type: integer
            format: int64
          name:
            type: string
            example: Alice